spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#debug=true


spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.web.resources.static-locations=file:src/main/resources/static/
spring.thymeleaf.cache=false
mybatis.mapper-locations=classpath:mapper/*.xml

# 画像アップロード容量制限（追加）
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB